[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'example'
version = '1.0.0'

[tool.hatch.build.targets.wheel]
packages = ['example']

[project.entry-points.pkg_config]
example = 'example.pkgconf'
